URL_ATTRIBUTES = [
    ('a', 'href'),
    ('applet', 'codebase'),
    ('area', 'href'),
    ('blockquote', 'cite'),
    ('body', 'background'),
    ('del', 'cite'),
    ('form', 'action'),
    ('frame', 'longdesc'),
    ('frame', 'src'),
    ('iframe', 'longdesc'),
    ('iframe', 'src'),
    ('head', 'profile'),
    ('img', 'longdesc'),
    ('img', 'src'),
    ('img', 'usemap'),
    ('input', 'src'),
    ('input', 'usemap'),
    ('ins', 'cite'),
    ('link', 'href'),
    ('object', 'classid'),
    ('object', 'codebase'),
    ('object', 'data'),
    ('object', 'usemap'),
    ('q', 'cite'),
    ('script', 'src'),
    ('video', 'src'),
    ]


POPCORN_JS_ASSETS = [
    'external/popcorn-js/popcorn.js',
    'external/popcorn-js/build/jslint-check.js',
    'external/popcorn-js/build/jslint.js',
    'external/popcorn-js/demos/semantic_video/popcorn.applyclass.js',
    'external/popcorn-js/effects/applyclass/popcorn.applyclass.js',
    'external/popcorn-js/ie8/popcorn.ie8.js',
    'external/popcorn-js/modules/locale/popcorn.locale.js',
    'external/popcorn-js/modules/parser/popcorn.parser.js',
    'external/popcorn-js/modules/parser/data/parseMissing.json',
    'external/popcorn-js/modules/parser/data/parserAudio.json',
    'external/popcorn-js/modules/parser/data/parserData.json',
    'external/popcorn-js/modules/player/popcorn.player.js',
    'external/popcorn-js/modules/sequence/popcorn.sequence.js',
    'external/popcorn-js/modules/sequence/build/jshint-check.js',
    'external/popcorn-js/modules/sequence/build/jslint-check.js',
    'external/popcorn-js/modules/sequence/build/post-compile.js',
    'external/popcorn-js/modules/sequence/build/uglify.js',
    'external/popcorn-js/modules/sequence/build/lib/jshint.js',
    'external/popcorn-js/modules/sequence/build/lib/jslint.js',
    'external/popcorn-js/modules/sequence/build/lib/parse-js.js',
    'external/popcorn-js/modules/sequence/build/lib/process.js',
    'external/popcorn-js/modules/sequence/build/lib/squeeze-more.js',
    'external/popcorn-js/modules/timeline-sources/popcorn.timeline-sources.js',
    'external/popcorn-js/parsers/parserJSON/popcorn.parserJSON.js',
    'external/popcorn-js/parsers/parserJSON/data/audio.json',
    'external/popcorn-js/parsers/parserJSON/data/data.json',
    'external/popcorn-js/parsers/parserJSON/data/video.json',
    'external/popcorn-js/parsers/parserSBV/popcorn.parserSBV.js',
    'external/popcorn-js/parsers/parserSRT/popcorn.parserSRT.js',
    'external/popcorn-js/parsers/parserSSA/popcorn.parserSSA.js',
    'external/popcorn-js/parsers/parserTTML/popcorn.parserTTML.js',
    'external/popcorn-js/parsers/parserTTXT/popcorn.parserTTXT.js',
    'external/popcorn-js/parsers/parserVTT/popcorn.parserVTT.js',
    'external/popcorn-js/parsers/parserXML/popcorn.parserXML.js',
    'external/popcorn-js/players/soundcloud/popcorn.soundcloud.js',
    'external/popcorn-js/players/vimeo/popcorn.vimeo.js',
    'external/popcorn-js/players/youtube/popcorn.youtube.js',
    'external/popcorn-js/plugins/attribution/popcorn.attribution.js',
    'external/popcorn-js/plugins/code/popcorn.code.js',
    'external/popcorn-js/plugins/documentcloud/popcorn.documentcloud.js',
    'external/popcorn-js/plugins/facebook/popcorn.facebook.js',
    'external/popcorn-js/plugins/flickr/popcorn.flickr.js',
    'external/popcorn-js/plugins/footnote/popcorn.footnote.js',
    'external/popcorn-js/plugins/gml/popcorn.gml.js',
    'external/popcorn-js/plugins/googlefeed/popcorn.googlefeed.js',
    'external/popcorn-js/plugins/googlemap/popcorn.googlemap.js',
    'external/popcorn-js/plugins/image/popcorn.image.js',
    'external/popcorn-js/plugins/lastfm/popcorn.lastfm.js',
    'external/popcorn-js/plugins/linkedin/popcorn.linkedin.js',
    'external/popcorn-js/plugins/lowerthird/popcorn.lowerthird.js',
    'external/popcorn-js/plugins/mustache/popcorn.mustache.js',
    'external/popcorn-js/plugins/openmap/popcorn.openmap.js',
    'external/popcorn-js/plugins/pause/popcorn.pause.js',
    'external/popcorn-js/plugins/processing/popcorn.processing.js',
    'external/popcorn-js/plugins/rdio/popcorn.rdio.js',
    'external/popcorn-js/plugins/subtitle/popcorn.subtitle.js',
    'external/popcorn-js/plugins/tagthisperson/popcorn.tagthisperson.js',
    'external/popcorn-js/plugins/text/popcorn.text.js',
    'external/popcorn-js/plugins/timeline/popcorn.timeline.js',
    'external/popcorn-js/plugins/tumblr/popcorn.tumblr.js',
    'external/popcorn-js/plugins/twitter/popcorn.twitter.js',
    'external/popcorn-js/plugins/webpage/popcorn.webpage.js',
    'external/popcorn-js/plugins/wikipedia/popcorn.wikipedia.js',
    'external/popcorn-js/plugins/wordriver/popcorn.wordriver.js',
    'external/popcorn-js/tools/cleaner.js',
    'external/popcorn-js/tools/jslint-cmdline.js'
    ]


BUTTER_ASSETS = [
    'css/butter.ui.css',
    'css/butter.ui.deprecated.css',
    'css/manual-test-styles.css',
    'src/butter.js',
    'src/config.js',
    'src/default-config.json',
    'src/dependencies.js',
    'src/main.js',
    'src/modules.js',
    'src/core/comm.js',
    'src/core/config.js',
    'src/core/eventmanager.js',
    'src/core/logger.js',
    'src/core/media.js',
    'src/core/page.js',
    'src/core/popcorn-wrapper.js',
    'src/core/target.js',
    'src/core/track.js',
    'src/core/trackevent.js',
    'src/core/views/media-view.js',
    'src/core/views/track-view.js',
    'src/core/views/trackevent-view.js',
    'src/cornfield/module.js',
    'src/dialog/dialog-comm.js',
    'src/dialog/iframe-dialog.js',
    'src/dialog/modal.js',
    'src/dialog/window-dialog.js',
    'src/editor/editor.js',
    'src/editor/module.js',
    'src/plugin/module.js',
    'src/plugin/plugin-list.js',
    'src/plugin/plugin.js',
    'src/timeline/media.js',
    'src/timeline/module.js',
    'src/timeline/scrollbars.js',
    'src/timeline/scrubber.js',
    'src/timeline/status.js',
    'src/timeline/timebar.js',
    'src/timeline/track-container.js',
    'src/timeline/trackhandles.js',
    'src/timeline/zoombar.js',
    'src/ui/context-button.js',
    'src/ui/header.js',
    'src/ui/logo-spinner.js',
    'src/ui/page-element.js',
    'src/ui/position-tracker.js',
    'src/ui/toggler.js',
    'src/ui/ui.js',
    'src/ui/widget/textbox.js',
    'src/util/css.js',
    'src/util/dragndrop.js',
    'src/util/lang.js',
    'src/util/scrollbars.js',
    'src/util/time.js',
    'src/util/xhr.js'
    ]
